os: linux
language: cpp
compiler: gcc
dist: focal

addons:
   apt:
     packages:
       - cmake
       - libgtest-dev
       - g++
       - libpng-dev
       - libjpeg-turbo8-dev
       - libtiff-dev
       - libglew-dev
       - qt5-default
       - libqt5opengl5-dev
       - libqt5svg5-dev
       - libqt5widgets5

matrix:
  include:
    - env: BUILD_TYPE="Release"
    - env: BUILD_TYPE="Debug"

env:
  global:
    - NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU"
    - BUILD_SYSTEM="`uname -s`"
    - BUILD_PROCESSOR="`uname -p`"
    - MVE_SOURCE=${TRAVIS_BUILD_DIR}
    - MVE_BUILD=${TRAVIS_BUILD_DIR}/build
    - MVE_INSTALL=${MVE_BUILD}/install
    - MVE_SOURCE_APP=$MVE_SOURCE/apps
    - MVE_BUILD_APP=${MVE_SOURCE_APP}/build

before_script:
    - mkdir --parent ${MVE_BUILD}
    - cd ${MVE_BUILD}
    - >
      cmake \
        -DCMAKE_INSTALL_PREFIX:PATH=${MVE_INSTALL} \
        -DMVE_BUILD_UMVE:BOOL=OFF \
        -DMVE_BUILD_APPS:BOOL=ON \
        -DMVE_BUILD_TESTS:BOOL=ON \
        -DGTest_DIR:PATH=${GTEST_INSTALL}/lib/cmake/GTest \
        -DCMAKE_BUILD_TYPE:BOOL=${BUILD_TYPE} \
        -DBUILD_SHARED_LIBS:BOOL=ON \
        . ${MVE_SOURCE}

script:
    - make install -j$(nproc) VERBOSE=1
    - make test

    # Test if it compiles as third party
    - cd ${MVE_SOURCE_APP}
    - mkdir --parent ${MVE_BUILD_APP}
    - cd ${MVE_BUILD_APP}
    - >
      cmake -DBUILD_SHARED_LIBS:BOOL=ON \
        -DMVE_BUILD_UMVE:BOOL=OFF \
        -Dmve_DIR:PATH=${MVE_INSTALL}/lib/cmake/mve \
        -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install \
        . ${MVE_SOURCE_APP}
    - make install -j 2 VERBOSE=1

# Before uploading the new cache archive
before_cache:
  - ccache -s

cache:
  ccache: true