os: linux
language: cpp
compiler: gcc
sudo: false

branches:
   only:
     - master

before_install:
   - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi

addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-6
       - cmake

before_script:
   - wget https://github.com/google/googletest/archive/master.zip -O /tmp/gtest.zip
   - unzip /tmp/gtest.zip
   - export GTEST_PATH=$PWD/googletest-master
   - mkdir $GTEST_PATH/build
   - pushd $GTEST_PATH/build
   - cmake ..
   - make gtest_main
   - popd

script:
    - make -j4 -Clibs/util
    - make -j4 -Clibs/mve
    - make -j4 -Clibs/sfm
    - make -j4 -Clibs/fssr
    - make -j4 test
    - ./tests/test
